mkdir C:\Instrument
mkdir C:\Instrument\bin
mkdir C:\Instrument\bin\Archive
mkdir C:\Instrument\Config
mkdir C:\Instrument\Config\Backup
mkdir C:\Instrument\Config\Installed
mkdir C:\Instrument\Data
mkdir C:\Instrument\DB_Data
mkdir C:\Instrument\DB_Tools
mkdir C:\instrument\Export
mkdir C:\Instrument\ExternalImages
mkdir C:\Instrument\Logs
mkdir C:\Instrument\ResultsData\Images
mkdir C:\Instrument\ResultsData\ResultBinaries
mkdir C:\Instrument\Software
mkdir C:\Instrument\Tools
mkdir C:\Instrument\Tools\.NET_4.7.2
mkdir C:\Instrument\Tools\Basler
mkdir C:\Instrument\Tools\BeckmanConnect
mkdir C:\Instrument\Tools\fciv
mkdir C:\Instrument\Tools\Omicron
