//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MotorSysTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MOTOR_SYS_TEST_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDR_VERSION2                    130
#define IDC_SCRIPT_EDIT                 1000
#define IDC_REAGENT_ARM_LBL             1001
#define IDC_REAGENT_ARM_UP_BTN          1002
#define IDC_REAGENT_ARM_DN_BTN          1003
#define IDC_REAGENT_ARM_PURGE_BTN       1004
#define IDC_REAGENT_DOOR_CLOSED_CHK     1005
#define IDC_UNLOCK_DOOR_BTN             1006
#define IDC_REAGENT_PACK_DETECTED_CHK   1007
#define IDC_REAGENT_HOME_CHK            1008
#define IDC_REAGENT_LIMIT_CHK           1009
#define IDC_CURRENT_LBL                 1010
#define IDC_THETA_POS_LBL               1011
#define IDC_THETA_POS_CURRENT_DISP      1012
#define IDC_THETA_POS_EDIT              1013
#define IDC_THETA_GOTO_POS_BTN          1014
#define IDC_THETA_HOME_CHK              1015
#define IDC_THETA_HOME_BTN              1016
#define IDC_RADIUS_POS_LBL              1017
#define IDC_RADIUS_POS_CURRENT_DISP     1018
#define IDC_RADIUS_POS_EDIT             1019
#define IDC_RADIUS_GOTO_POS_BTN         1020
#define IDC_RADIUS_HOME_CHK             1021
#define IDC_RADIUS_HOME_BTN             1022
#define IDC_GOTO_RTHETA_POS_BTN         1023
#define IDC_RELATIVE_MOVE_CHK           1024
#define IDC_SAMPLE_PROBE_LBL            1025
#define IDC_PROBE_UP_BTN                1026
#define IDC_PROBE_DOWN_BTN              1027
#define IDC_PROBE_INIT_BTN              1028
#define IDC_PROBE_HOME_BTN              1029
#define IDC_PROBE_HOME_CHK              1030
#define IDC_PROBE_POS_LBL               1031
#define IDC_PROBE_POS_CURRENT_DISP      1032
#define IDC_FINE_FOCUS_LBL              1033
#define IDC_FINE_FOCUS_UP_BTN           1034
#define IDC_FINE_FOCUS_DN_BTN           1035
#define IDC_COARSE_FOCUS_LBL            1036
#define IDC_COARSE_FOCUS_UP_BTN         1037
#define IDC_COARSE_FOCUS_DN_BTN         1038
#define IDC_FOCUS_POS_LBL               1039
#define IDC_FOCUS_POS_CURRENT_DISP      1040
#define IDC_FOCUS_POS_EDIT              1041
#define IDC_FOCUS_GOTO_POS_BTN          1042
#define IDC_FOCUS_HOME_CHK              1043
#define IDC_FOCUS_HOME_BTN              1044
#define IDC_FOCUS_GOTO_CENTER_BTN       1045
#define IDC_INST_TYPE_CHK               1046
#define IDC_LED_RACK1_LBL               1047
#define IDC_LED_RACK1_PATH_DISP         1048
#define IDC_LED_RACK1_GOTO_TOP_BTN      1049
#define IDC_LED_RACK1_CAL_TOP_BTN       1050
#define IDC_LED_RACK1_GOTO_CTR_BTN      1051
#define IDC_LED_RACK1_CAL_CTR_BTN       1052
#define IDC_LED_RACK1_GOTO_BOT_BTN      1053
#define IDC_LED_RACK1_CAL_BOT_BTN       1054
#define IDC_LED_RACK1_HOME_BTN          1055
#define IDC_RACK1_HOME_CHK              1056
#define IDC_LED_RACK2_LBL               1057
#define IDC_LED_RACK2_PATH_DISP         1058
#define IDC_LED_RACK2_GOTO_TOP_BTN      1059
#define IDC_LED_RACK2_CAL_TOP_BTN       1060
#define IDC_LED_RACK2_GOTO_CTR_BTN      1061
#define IDC_LED_RACK2_CAL_CTR_BTN       1062
#define IDC_LED_RACK2_GOTO_BOT_BTN      1063
#define IDC_LED_RACK2_CAL_BOT_BTN       1064
#define IDC_LED_RACK2_HOME_BTN          1065
#define IDC_RACK2_HOME_CHK              1066
#define IDC_ROW_EDIT                    1067
#define IDC_ROW_LBL                     1068
#define IDC_ROW_CURRENT_DISP            1069
#define IDC_COL_EDIT                    1070
#define IDC_COL_LBL                     1071
#define IDC_COL_CURRENT_DISP            1072
#define IDC_ROW_COL_GOTO_BTN            1073
#define IDC_ROW_COL_NEXT_BTN            1074
#define IDC_TUBE_LBL                    1075
#define IDC_TUBE_NUM_CURRENT_DISP       1076
#define IDC_TUBE_NUM_EDIT               1077
#define IDC_TUBE_GOTO_BTN               1078
#define IDC_TUBE_NEXT_BTN               1079
#define IDC_TUBE_FIND_BTN               1080
#define IDC_TUBE_DETECTED_CHK           1081
#define IDC_UPDATE_CURRENT_BTN          1082
#define IDC_RADIO_PLATE_SELECT          1083
#define IDC_PLATE_INIT_ERROR_CHK        1084
#define IDC_PLATE_DETECTED_CHK          1085
#define IDC_PLATE_CAL_BTN               1086
#define IDC_PLATE_EJECT_BTN             1087
#define IDC_PLATE_LOAD_BTN              1088
#define IDC_PLATE_INIT_BTN              1089
#define IDC_PLATE_DETECT_BTN            1090
#define IDC_PLATE_THETA_ADJUST_LEFT_BTN 1091
#define IDC_PLATE_THETA_ADJUST_RIGHT_BTN 1092
#define IDC_PLATE_RADIUS_ADJUST_IN_BTN  1093
#define IDC_PLATE_RADIUS_ADJUST_OUT_BTN 1094
#define IDC_PLATE_RADIUS_BACKLASH_EDIT  1095
#define IDC_PLATE_RADIUS_BACKLASH_LBL   1096
#define IDC_PLATE_RADIUS_BACKLASH_SET_BTN 1097
#define IDC_PLATE_THETA_BACKLASH_EDIT   1098
#define IDC_PLATE_THETA_BACKLASH_LBL    1099
#define IDC_PLATE_THETA_BACKLASH_SET_BTN 1100
#define IDC_RADIO_CAROUSEL_SELECT       1101
#define IDC_CAROUSEL_INIT_ERROR_CHK     1102
#define IDC_CAROUSEL_DETECTED_CHK       1103
#define IDC_CAROUSEL_CAL_BTN            1104
#define IDC_CAROUSEL_EJECT_BTN          1105
#define IDC_CAROUSEL_LOAD_BTN           1106
#define IDC_CAROUSEL_INIT_BTN           1107
#define IDC_CAROUSEL_THETA_ADJUST_LEFT_BTN 1108
#define IDC_CAROUSEL_THETA_ADJUST_RIGHT_BTN 1109
#define IDC_CAROUSEL_RADIUS_ADJUST_IN_BTN 1110
#define IDC_CAROUSEL_RADIUS_ADJUST_OUT_BTN 1111
#define IDC_CAROUSEL_THETA_BACKLASH_EDIT 1112
#define IDC_CAROUSEL_THETA_BACKLASH_LBL 1113
#define IDC_CAROUSEL_THETA_BACKLASH_SET_BTN 1114
#define IDC_RUN_SCRIPT_BTN              1115
#define IDC_STEP_NUM_DISP               1116
#define IDC_STEP_NUM_SPIN               1117
#define IDC_SCRIPT_LINE_LBL             1118
#define IDC_ERROR_CNT_LBL               1119
#define IDC_ERROR_CNT_DISP              1120
#define IDC_PAUSE_SCRIPT_BTN            1121
#define IDC_STOP_SCRIPT_BTN             1122
#define IDC_SCRIPT_PATH_EDIT            1123
#define IDC_LOAD_SCRIPT_BTN             1124
#define IDC_CLEAR_SCRIPT_BTN            1125
#define IDC_SAVE_SCRIPT_BTN             1126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
